<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TR00491W" failures="1" tests="1" name="Default test" time="228.202" errors="0" timestamp="2022-02-11T15:58:18 TRT">
  <testcase classname="courgette.api.testng.TestNGCourgette" name="parallelRun" time="227.931">
    <failure type="courgette.runtime.CourgetteTestFailureException" message="There were failing tests. Refer to the Courgette html report for more details.">
      <![CDATA[courgette.runtime.CourgetteTestFailureException: There were failing tests. Refer to the Courgette html report for more details.
]]>
    </failure>
  </testcase> <!-- parallelRun -->
</testsuite> <!-- Default test -->
